# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/dolby/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/dolby

PRODUCT_COPY_FILES += \
    vendor/xiaomi/dolby/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc

PRODUCT_PACKAGES += \
    vendor.dolby.hardware.dms@2.0 \
    libdapparamstorage \
    libdeccfg \
    libstagefright_soft_ac4dec \
    libstagefright_soft_ddpdec \
    libstagefrightdolby \
    libhwdap \
    libswgamedap \
    libswvqe \
    vendor.dolby.hardware.dms@2.0 \
    libdlbdsservice \
    vendor.dolby.hardware.dms@2.0-impl \
    vendor.dolby.hardware.dms@2.0-service
